name: Generate Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to generate changelog for (e.g., 0.2.0)'
        required: true
        default: '0.2.0'
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Generate Changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/generate_changelog.py \
            --version ${{ github.event.inputs.version || github.event.release.tag_name }} \
            --repo ${{ github.repository }} \
            --output docs/changelog.md

      - name: Commit changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/changelog.md
          git commit -m "docs: update changelog for ${{ github.event.inputs.version || github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin main
