name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest
    
    - name: Install dependencies
      run: |
        uv sync --dev
    
    - name: Run ruff format check
      run: |
        uv run ruff format --check .
    
    - name: Run ruff lint
      run: |
        uv run ruff check .
    
    - name: Run ruff check with --fix
      run: |
        uv run ruff check --fix .
    
    - name: Check for any remaining issues
      run: |
        uv run ruff check .
        uv run ruff format --check . 